### ISSUE TITLE
link field type array url may not be set

### ISSUE THREAD

**Issue by ohiowebpro** [wordpress-premium/advanced-custom-fields-pro#1]
When using a Link field type in a custom block, I am getting a warning on the admin page block builder: Warning: Undefined array key "url" in /var/www/html/wp-content/plugins/advanced-custom-fields-pro/includes/api/api-helpers.php on line 2871

I can update the line to fix using:
$use_path = isset($attachment['filename']) ? $attachment['filename'] : (isset($attachment['url']) ? $attachment['url'] : '');

Instead of 
$use_path     = isset( $attachment['filename'] ) ? $attachment['filename'] : $attachment['url'];

All plugins and wordpress are up to date. I am using Roots Sage for the theme development and using ACF method for custom blocks.

**Comment by thaikolja** [comment]
If you use Sage, do you also use Bedrock and install the plugin via PHP Composer?

**Comment by ohiowebpro** [comment]
> If you use Sage, do you also use Bedrock and install the plugin via PHP Composer?

No, I am  using ACF pro as a plugin, not using it in composer.

**Comment by ohiowebpro** [comment]
Removing issue
